# Generated by Django 3.2.16 on 2022-12-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rappel_date', '0002_alter_notification_anniversaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='anniversaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rappel_date.anniversaire'),
        ),
    ]
